title: Nerd Weekend!
author: "Ian"
description:  >- # this means to ignore newlines until next configuration
  I'm not a *player*, I'm a *gamer*.
  Players get chicks.
  I get achievements.

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed